jenkinsci/amazon-ecs-plugin

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
Current Plugin use us-east-1 region only, so this pull request support other AWS region. 
Specify AWS region in Jenkins System Setting screen.
@ndeloof #6 rebase this pull request.
> Support AWS region. Setting AWS region in jenkins system setting screen.

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
* integrated support for using the proxy configured by
Jenkins.getInstance().proxy
> JENKINS-33928: Communication to AWS API should support HTTP proxies

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
[JENKINS-36857] Sleep 1000 ms between 2 interactions with AWS ECS API to create the ECS Task Definition + Improve log messages 
Sample log message: 1 second between each task definition creation
```
Jul 27, 2016 9:36:28 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSCloud 
Create cloud ecs-cloud on ECS cluster arn:aws:ecs:us-east-1:564007293907:cluster/default on the region us-east-1
Jul 27, 2016 9:36:28 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate setOwer
Slave ecs-template-1 - Created Task Definition: arn:aws:ecs:us-east-1:564007293907:task-definition/jenkins-slave:1212
Jul 27, 2016 9:36:29 AM INFO com.cloudbees.jenkins.plugins.amazonecs.ECSTaskTemplate setOwer
Slave ecs-template-2 - Created Task Definition: …
```
> [JENKINS-36857] Sleep 1000 ms between 2 interactions with AWS ECS API

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
Errors were introduced into `ECSService.registerTemplate(...)` during https://github.com/jenkinsci/amazon-ecs-plugin/commit/d2bc8168db56fe606dea5f4cf96bf7ee2b0ad6fb. These errors manifest in two circumstances:
1. There are no task definitions for a given family, or
2. there are more than 100 task definitions for a given family.
In the first case task creation fails because the system tries to retrieve an element from an empty queue. In the second case the system never exits a while-loop and runs out of memory.
This PR resolves both issues. In the former case this PR only tries to retrieve the last element from the queue if the queue is non-empty. In the latter case, the result-set tokens are used to retrieve successive subsets of the complete result-set.
> Use last token and don't try and dereference an empty list

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-dnsSearchDomains.html
- Define dns search domains (that corresponds to docker run `--dns-search` option)
> Add DnsSearchDomains option

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/PortMappingEntry/help-containerPort.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/PortMappingEntry/help-hostPort.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/PortMappingEntry/help-protocol.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-portMappings.html
This PR adds Port Mapping configuration options for the ECS container definition.
> Adding Port Mapping options for task templates

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
Quick pass at adding Container User to the config. Tested on my Jenkins and it works.
> Add container user

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
https://issues.jenkins-ci.org/browse/JENKINS-47422
> [JENKINS-47422] Fix NPE if templates is null

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
This PR should fix the plugin when migrating from a version without Launch type.
> Fixing null launchType usage

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
When a Task is not responding, for example when it hangs or is no longer running, then the computer will still be listed in the Jenkins build executors as offline and can still be consuming resources in an ECS Cloud, preventing new tasks from starting.
This PR will terminate these unresponsive tasks by checking if the Response Time Monitor has marked the computer as offline, this will stop the Task in ECS and remove it from the Jenkins build executor list, freeing resources.
Let me know if I should add a flag to enable this behavior.
> JENKINS-37597 Remove Tasks which are not responding

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
This change introduces the existing OnceRetentionStrategy and replaces the own implementation `deleteAfterFinished`.
> Use OnceRetentionStrategy

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-awsVpcNetworkMode.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-networkMode.html
Co-authored-by: Stephen Reddel <sreddel@lilemmson.co.uk>
> Enabling use of awsvpc network mode with the EC2 launch type

- README.md
- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/DefaultInProvisioning.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSComputer.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/InProvisioning.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/Messages.properties
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
* Separate logic of launching the ECS task into new ECSLauncher
* Provide consistent logging with agent name prefix
* Provide additional information in logs (like taskArn, clusterArn, containerInstanceId)
* Have unit tests for the most critical parts
> Introduce ECSLauncher

- README.md
Changed Readme.md to clarify the relationship between label and inheritFrom.
> Clarified template Inheritance

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
Add checking if custom task definition exists from issue #98.
> add non-ignoring custom task definition in pipeline

- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-image.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly
> This fixes issue #110

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-sharedMemorySize.html
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
Adding an option for `sharedMemorySize` (in MiB) which sets it for the ECS template and has been supported since March 2018.
> Adding Shared Memory Size options to set it within ECS

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
https://github.com/jenkinsci/amazon-ecs-plugin/issues/131 Fix issue mentioned here
> Fix do not remove custom task.

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
This change generates the agent name as soon as possible, so that all logs show the unique agent name instead of just the cloud or label name. This helps in correlating provisioning events when looking at logs.
This also changes the agent name format to `cloud-label-random`, so we can tell what label a particular agent belongs to, when we have N agent types for 1 label.
> Generate the agent name earlier

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
The annotations weren't being activated and testing indicated that it clearly was not a condition of success
> #139 - Remove jealous null checks 

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
Hi,
I'm building a custom ECSCloud out of this plugin for some very specific needs.
To avoid duplicating everything, I just split the content of ECSLauncher.launch so I can capture the Task at some point.
I also made ECSService class public.
> Changes to enable ECSCloud overrides

- README.md
Add closing ticks (```)  to "Scripted Pipeline examples"
> Add closing ticks (```)  to "Scripted Pipeline examples" 

- examples/fargate/docker/files/jenkins.yaml
- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-enableExecuteCommand.html
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Implement Feature Request #245
> Add enable execute command

- .gitignore
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSProvisioningStrategy.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
Update the default number of agents to unlimited. Also, updated the terminology from Node to Agent
> Unlimited Agents

- README.md
- examples/fargate/cloudformation-master.yaml
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/BaseAWSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/EFSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Support EFS volume mounts, including new EFS Access Point API
Added support for EFS volume mounts as part of the ECS configuration.
Resolves issue #181
This is a re-opening of #210 now that this repo has maintainers, hopefully we can get this merged this time around.
I've been using this code in production for several months without any issue, and have had others manually build and use it successfully as well (see original PR).
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant pull requests, esp. upstream and downstream changes
> Add support for EFS Mount Points

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-tags.html
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
This PR aims to add support for adding tags on AWS tasks and task definition created by plugin.
Resolves issue [**#261**](https://github.com/jenkinsci/amazon-ecs-plugin/issues/261)
> Add support for Tags

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
> Fixing a spelling mistake for the setter method on capacity providers

- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
Fixed a typo in description text for taskPollingIntervalInSeconds throtting -> throttling
> Fix typo throtting -> throttling

- pom.xml
This avoids pulling the monolith `aws-java-sdk` in favor of smaller plugins.
> Depends on fine-grained aws-java-sdk artifacts

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
fixes exceptions described in issues #290 and #291 by checking if tags are null before passing to task definition.
> Fix tags null pointer exception by checking if tags are null

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly
Adds support for placement strategies in declarative pipelines 
Closes #281
> Add support for placementStrategies

- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java
- src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-ulimits.html
- src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Add Ulimits Capability to the plugin to configure the desired Ulimit: 
https://github.com/jenkinsci/amazon-ecs-plugin/issues/257
The plugin was tested in this [Jenkins instance](http://54.146.59.68:8080/) by building the .hpi file and also internally.
> Add Ulimits capability to aws task creation

- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
```[tasklist]
```
In our analysis of the project, we observed that the test `ECSClodTest.removeJunkTemplateProducesNoError` contains an unnecessary stubbing. 
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html). 
We propose below a solution to remove the unnecessary stubbing.
> Removed 1 unnecessary stubbing in ECSCloudTest.java

- README.md
* Make some minor readbility changes
* Add a link to another useful example
Documentation change only, so no tests required.
```[tasklist]
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```
> Documention tweaks in README

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/release-drafter.yml
- .github/workflows/jenkins-security-scan.yml
- .github/workflows/release-drafter.yml
- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- pom.xml
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
- src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Update this plugin to conform to the latest best practices for Jenkins plugins from the Jenkins archetype, including building/testing on Java 17/21.
> Refresh plugin for August 2023
