jenkinsci/amazon-ecs-plugin

pom.xml, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
These changes allows to configure the container to be run in [privileged](https://docs.docker.com/engine/reference/run/#runtime-privilege-linux-capabilities-and-lxc-configuration) mode.
=> Added privilege mode

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
This is a proposed fix to https://issues.jenkins-ci.org/browse/JENKINS-32321
The call to AWS to delete an ECS task is wrapped in a try catch because in some cases (either legitimate or not) the task doesn't exist.
If not caught then there's some ugly behaviour where the exception will prevent Jenkins from starting or stop you from saving configurations in the UI
=> [JENKINS-32321] catch task missing exceptions

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
* Define volumes the instance exports
* Define mount points the container imports
=> Add volumes and mount points

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
This PR allows the log driver to be set on a Task to something other than the default of JSON
If you're keen you can switch to the syslog driver & then pull logs from the EC2 boxes which are backing the ECS cluster so that you can see what the Jenkins Remoting Slave Jar is up to (or not up to if it's crashing, OOMing, or otherwise misbehaving)
=> [JENKINS-32741] Allow the log driver to be set for a Task

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
The ECS API assumes the default cluster for stopping a task unless otherwise specified. This patch specifies the cluster for all StopTask requests.
Fixes [JENKINS-32895](https://issues.jenkins-ci.org/browse/JENKINS-32895)
=> [JENKINS-32895] Supply cluster ARN when stopping tasks

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
This PR updates the `ECSTaskTemplate` to set the logDriver using the `@DataBoundSetter ` annotation.  A guard on the input parameter ensures that the logDriver is null... not just empty. :wink:  These changes address a small bug introduced in commit @65880c7b and merged into master in PR #16.  
PR #16 updates the amazon-ecs plugin with the ability to set the log Driver for the ECS Task.  However, when the logging driver is left empty, the following errors occur:
``` bash
Caused by: java.lang.RuntimeException: Failed to instantiate class com.cloudbees.jenkins.plugins.amazonecs.ECSCloud from {"name":"some-cloud","credentialsId":"f02646c5-368a-4845-a157-fa67a07f3d1d","regionName":"us-east-1","cluster":"arn:aws:ecs:us-east-1:xxxxxxxxxx:cluster/test-cluster","tunnel":"","templates":{"label":"si …
```
=> Updates the ECSTaskTemplate to properly set logDriver to null when empty

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
With this change one can supply an alternative Jenkins Urls the cloud slave uses to callback to Jenkins. This can be useful when combined with the tunnel option to enable slaves which call back to the master over a dedicated connection.
=> Alternative Jenkins URL for callback from cloud slaves

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
* make the provisioner wait for sufficient cluster resources before
* creating tasks. This avoids failed tasks resulting in stale Jenkins
* slaves.
* make the slave timeout configurable
* gracefully remove a slave from Jenkins in case of task startup
failure
* use the cluster ARN to communicate with AWS to avoid letting
* Amazon choose the default cluster
* refactor ECSCloud to move AWS related stuff to a separate class
=> Scalability improvements

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-templatename.html
Hi @roehrijn 
This fix comes out from the discussion that was held in #27 about having a more flexible task definition name. I've made the changes as requested summarised as below:
- Add a new 'Template Name' configuration that has to be defined.
- Add checking to make sure Cloud and Template Name are in the right format
- Use the combination of template name and cloud name when defining a task definition.
Thanks
=> Task definition name based on cloud and Template name

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
Creating ECSSlave with null label is wasting of resource, because ECSSlave
is instantiate with EXCLUSIVE mode. Job with null label will not
scheduled to it
It's even worse, it will keep trying to create more idle ECSSlave and
consume all resource in cluster :(
How to reproduce this problem:
- Make sure that amazon ecs plugin is the only one agent that active (by setting master executor number to 0, disable other cloud, ..., etc)
- Create a template (just use jenkinsci/jnlp-slave image) with arbitary label (or without label)
- Create simple job (without label) and run it
- BOOM!!, ecs plugin will keep trying to create ecs task and the job will not scheduled to any those agent because the agent is exclusive
right now, the only way to prevent this from happening is to make sure that every …
=> Don't provision if label is null

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSComputer.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
AmazonECSClient throw Runtime exception when error, so
https://github.com/jenkinsci/amazon-ecs-plugin/blob/5090b4deedad9c9ec142c44874249884a5a66346/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java#L271
maybe skipped and node will never be deleted
see [runTask](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/AmazonECSClient.html#runTask-com.amazonaws.services.ecs.model.RunTaskRequest-) and [stopTask](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ecs/AmazonECSClient.html#stopTask-com.amazonaws.services.ecs.model.StopTaskRequest-) documentation, they throw [Unchecked exception](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html)
=> Change how node removal work

pom.xml, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
This will add the possibility to assign an IAM role to the slave ECS task definition.
To do this I needed to update the dependency to the newer AWS SDK, because adding a task role is not supported in the old version.
=> Add taskRoleArn configuration option

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-taskrole.html
Sorry for creating a second pull request for the same feature. It seems like the other PR is not moving.
- I've used the changes by `joh-m`
- Updated the logic to check if task role is specified and only then, add it to the register task def request
- Added a helpfile for the taskRoleArn field
**A few notes**:
I've packaged this plugin and tested it on a Jenkins master running on Amazon ECS. 
There is a gotcha with regards to passing a role ARN to a task:
- The role assumed by the jenkins master (task or ec2-instance) needs to have an `iam:PassRole` policy for any roles which you wish to assign to a slave task
Otherwise you'll get an error similar to the following:
`User: A is not authorized to perform: iam:PassRole on resource: B`
Where A is the arn of the role assumed by the jenkins …
=> Allow Specification of Task Role ARN for ECS Slave Templates

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-memory.html, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-memoryReservation.html
Provide support for setting of the soft memory (memoryReservation) and or the hard memory (memory) settings when creating the task container.
Even though the documentation for the API specifies that it's possible to not set either of these, AWS prevents creation of task templates which do not have one of either memory or memoryReservation set.
By adding the soft memory setting it means that you can have a container spawn & use more than the memory reservation.
In my context setting the hard limit was leading to the kernel oom-killer process often killing the Jenkins Slave Agent JVM & I'd much prefer this not to happen.
The soft limit is a cue to the scheduler to not overcommit memory, so it's fair enough that's it's there
=> JENKINS-40300: Add MemoryReservation to set soft memory limits on the containers

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
This pull request fixes JENKINS-39220 by using withNextToken.  Additionally, all cluster ARNs are alphabetically sorted in the dropdown box.
=> JENKINS-39220: list all available ECS cluster (instead of first 100)

README.md
I believe the link to the Git plugin is a copy-paste mistake.
=> Fix link to EC2 plugin wiki page

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
- I found bugs that DNS search domains cannot be registered with task definition.
- I had made a mistake in resolving conflict on this commit and it was merged (sorry....): https://github.com/jenkinsci/amazon-ecs-plugin/commit/7039fc91c6984279870f29728657fa10a1071e98#diff-b6ed2a1d9bd787de97cfb63106ab68f3L540
=> Fix task definitions registory (add DNS search option)

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
Fixes the issue:
```
WARNING: Unexpected exception encountered while provisioning agent ECS Slave generic
com.amazonaws.services.ecs.model.ClientException: The user value contains invalid characters. Enter a value that matches the pattern ^([a-z0-9_][a-z0-9_-]{0,30})$ (Service: AmazonECS; Status Code: 400;
```
=> Treat empty username as null

README.md
The readme doesn't render properly - this updates the URL that points to the jira project so that it will render correctly.
Before:
After:
=> Fix readme.md to use proper wiki URL

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-externalTaskDefinition.html
This PR is similar in spirit to PR #45, but is more flexible. In essence, it allows you to set a "Task Definition Override" that will instruct the ECS plugin to look for the task definition in ECS, and will prevent the plugin from creating or updating task definitions.
The motivation for this PR is the lack of options in the ECS plugin's task definition screen. For example, we can't add sidecar containers through the Jenkins UI. Rather than trying to duplicate the UI of the AWS Console in Jenkins, we can just allow users to manage their task definitions through the AWS Console itself, or through any other mechanism. (I'm using terraform to manage the task definitions, which is working very well.)
The changes here are actually quite straightforward:
- Provide a "Task Definition Override" …
=> Allow using externally-managed task definitions

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSComputer.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java
Previously, Jenkins would only run one task per template.  This meant that even though ECS could be used to spin up a dozen containers to run a dozen parallel jobs, if they used the same template, then they would all pile up and run one at a time.
I got around this by having the Computer instances tell Jenkins that they were not accepting any new tasks once they had started working on a task. This way, Jenkins would see a busy ECS slave node as completely done and spin up a new one.
The logging in ECSCloud.java is for parity with `docker-plugin`.
=> Allow multiple slaves to run with the same template

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
This PR adds support for the newly introduced LaunchType, Fargate.
=> Adding support to Fargate

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-executionRole.html
Hi,
I've taken the latest version and tried to run the FARGATE launch type.
Followed all the FARGATE rules, but got the following exception:
```
com.amazonaws.services.ecs.model.ClientException: Fargate requires task definition to have execution role ARN to support ECR images. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: f8232776-6025-11e8-9c16-339a4240ed65)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
at …
```
=> Added executionRole field for fargate support

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
When an agent is being provisioned, the ECSCloud starts the ECS task which runs the agent and waits for the agent to become online. If the agent does not become online, then the agent is removed from Jenkins. However, in some cases the ECS task may still be running which leaks cluster resources. For example, we have observed JNLP agents which have hung during startup and continue to run but not connect.
This PR terminates the task if it did not become online during provisioning, preventing leaking of cluster resources from failed provisioning attempts.
If the task is not running, then `deleteTask` simply logs and continues.
=> Delete Task if it failed to connect during provisioning

src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave/configure-entries.jelly
When you click on Agent -> Configure, a 5xx error page is shown. This PR adds the missing jelly page.
=> Add configure page for agent

src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-executionRole.html
if an admin opens the jenkins system config, all the build slave configs will have the "Task Execution Role ARN" field reset back to their default value if this field was empty.
=> Problems with EC2 as the launch type (not fargate). 

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
This is a quick fix to allow overrides in declarative mode for some mixed-case parameters (such as inheritFrom).
Changes:
- removed toLowerCase() in isAllowedOverride method
Tests:
- tried to specify not allowed parameter: failed as expected
- specified only allowed included mixed-case ones: worked as expected
=> Fixed Case insensitive match of overrides

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
This now allows us to utilise declarative configuration for fargate ecs agents.
It does appear that cpu / memory have to be specified as well in the declaration but I've not had a chance to look into that yet. 
Fixes #95
=> Add executionRole support in declarative agent for fargate use

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly
When deploying a large number of ECS agents (200+ concurrently), AWS often throttles ECS API calls due to the large number of `DescribeTasks` calls being made waiting for the agent task to enter the RUNNING state: https://github.com/francoiscampbell/amazon-ecs-plugin/blob/1646c51035390d44c8be8edfa69cf98e48cc1354/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java#L122
This PR makes this polling interval customizable, since a small delay in agents coming online is acceptable in exchange for not being subject to AWS throttling.
=> Make ECS task polling interval customizable

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java
Since `describeTask` can return `null`, we can't call `task.getTaskArn()` on every iteration. Instead, let's keep separate references to the return values of `runECSTask` and `describeTask`.
=> Fix NPE when provisioning agents

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java
This fixes a memory leak bug that manifests itself when creating ECS Task templates on a pipelined job while also using task definition overrides. You can see this bug in effect by running a pipeline job like so
```
ecsTaskTemplate(
cloud: 'YourCloudHere',
label: "LabelThatShouldOnlyExistDuringJobRun",
name: 'name',
containerUser: 'jenkins',
remoteFSRoot: '/home/jenkins',
overrides: [],
taskDefinitionOverride: 'arn:aws:ecs:us-east-1::task-definition/${env.task}',
) {
...
}
```
When the pipeline is running you should be able to run ```Jenkins.instance.getLabels()``` in the Jenkins script console and see the label. When the pipeline job finishes this label should be cleaned up, but running the snippet again will show it lingers. I believe this bug can be tracked to this PR …
=> Remove dynamic task templates from the template map

Changelog.md, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-uniqueRemoteFSRoot.html, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
Hello :wave:,
While using this plugin we ended up in the situation where multiple ECS agents running on the same EC2 instance ended up sharing the same workspace while preforming `parallel` stages.
The setup:
* We run dockerised agents on an ECS cluster using this plugin.
* The (contained) ECS agents can start further containers.
To do so, they have access to the host's docker deamon socket.
* For the ECS agent to share the workspace with the containers it creates on the host we mount the agent workspace of every ECS agent to the matching path on the host (any other setup leads the steps in the containers created by ECS agents to not find needed files).
Proposed solution in this PR: append a unique name (the agent name) to the remote FS root parameter so all ECS agents can mount the same …
=> Unique paths for remote filesystem root

src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-image.html, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly
The `jenkins\jnlp-slave` image has been renamed to `jenkins\inbound-agent`. This updates the default image name and documentation to point to the new image.
=> Update the default agent name to the new name for the image

README.md, pom.xml, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/SerializableSupplier.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSServiceTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
#139 
This set of changes includes numerous fixes 
- When getting an error from AWS after a task is complete (like if it can't find the task family), don't try to find a task version on `null`
- If `ECSCloud.provision` could not find a template, this produced an NPE
- added more, and clearer logs
- *important* fixed the match logic for `canProvision` as it was using `String.matches` instead of `LabelAtom.matches` which is a regex match not a set intersection. In addition, the match was backwards.
- *Important* under fargate, "addTemplateDyanamic" was simply not merging at all - this is fixed. 
- adds mocking to the ECSCloudTest so that tests don't try to create AMZN resources (this should be a seperate test) as this may discourage OSS devs from testing if they think it will cost them …
=> #139 Fix fargate run/merge issue, add tests, merge in pipeline scripts config

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java
When an ECS task definition override is used, the template name and memory fields are ignored and shouldn't be validated.
Before:
After:
To reproduce:
- Create a new task template in a new or existing cloud
- See the failing validation because the name and memory fields are empty
- Type in anything in the task definition field (we don't validate that it's a valid ARN or that the taskdef exists at this point)
- Tab or click out of the field to trigger validation
- See that the validation errors on template name and memory disappear
=> Ignore template name and memory form field validation if a task definition override is used

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java
If you setup a parent template with entrypoint = /bin/bash and a second template with inheritFrom = <LABEL_OF_PARENT> with no entrypoint, the second template has an empty entrypoint.
So parent entrypoint is lost.
The downside is that is you want to clear the entrypoint, you can't.
But you actually can't clear any parent option for now, only the entrypoint has a different behavior.
=> Entrypoint override is lost when using inheritFrom

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java
Prevent the ECSService object being serialized with ECSCloud.  It will be automatically re-instantiated when not defined via the `getEcsService()`method.  This prevents an NPE occuring during Jenkins startup due to the Supplier in ECSService not being defined.
#187
=> Make ECSService transient - prevent NPE

README.md, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/help-assumedRoleARN.html, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
New UI option to provide an `Assumed Role ARN`
> ARN of IAM role assumed when making AWS API calls to create ECS agents. Use for scenarios such as creating ECS agents in a different AWS account.
I have verified this works, by assuming a role in another AWS account and provisioning a Jenkins agent.
Let me know if I missed anything. Thanks :)
resolves #220 
resolves #103
=> Add assumed role option

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java
#234 Add configured label and template name as default tags
Unfortunately there are no existing unit tests right now, at least not for the ECSService class.
The change is a simple extension of the AWS task definition sent to ECS.
I could successfully do a local (manual) integration test of the new feature.
=> Add configured label and template name as default tags

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-kernelCapabilities.html, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
This commit adds option to add kernel capabilities for ECS task definition.  Relevant GutHub issue is [#241](https://github.com/jenkinsci/amazon-ecs-plugin/issues/241).
It's described [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters).
Currently, Fargate supports just SYS_PTRACE kernel capability, EC2 ECS supports everything on the link above.
I have tested this with Fargate, and it works fine, haven't tested with EC2 ECS.
NOTE: This adds option to add kernel capabilities, I haven't implemented option to drop capabilities, but should be easy to add, though I think it's rarely being used.
=> Add support for KernelCapabilities

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-cpuArchitecture.html, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-operatingSystemFamily.html, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Add [operatingSystemFamily](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html) and [cpuArchitecture](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html) parameters support to supply Runtime platform for Fargate launch type.
related to: https://github.com/jenkinsci/amazon-ecs-plugin/issues/252
=> Add operatingSystemFamily and cpuArchitecture parameters support.

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/help-ephemeralStorageSizeInGiB.html, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Enable EphemeralStorageSize allows you to increase the size of the root
disk up to 100GB.  Only support for Fargate 1.4.0 and above.
As this requires AWS java SDK version 2.11.1008 some extra depdencies
needed to be updated.
=> Support Fargate EphemeralStorageSize

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud/config.jelly, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
Removing hardcoded number of executors per agent and adding ability for users to define this via the cloud configuration settings page.
- Updated ECS Cloud resource to enable users to define numExecutors value in cloud configuration settings. Defaults to 1 as per existing hardcoded value.
- Updated initiation of  NodeProvisioner.PlannedNode to pass in new numExecutors value instead of the previously hardcoded one.
- Pulled from [https://github.com/plumbuma/amazon-ecs-plugin/commit/3ebfefa5b4f1d2e249f147aca6257b83219282dd](https://github.com/plumbuma/amazon-ecs-plugin/commit/3ebfefa5b4f1d2e249f147aca6257b83219282dd)
- Feature request - [https://github.com/jenkinsci/amazon-ecs-plugin/issues/265](https://github.com/jenkinsci/amazon-ecs-plugin/issues/265)
=> Added ability to define number of executors on agents

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java
This PR adds `synchronize` to the launch method to prevent multiple threads simultaneously spinning up the same computer.
In a worse case scenario, simultaneous calls to launch will cause containers to spin up in ECS that will attempt to connect to Jenkins forever, but will fail with with the following traceback
```
INFO: [JNLP4-connect connection to redacted-ip] Local headers refused by remote: Unknown client name: redacted-computer-name
Sep 13, 2022 3:01:05 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Unknown client name: redacted-computer-name
at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223 …
```
=> make launch method thread safe

README.md, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecution.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep/config.jelly, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplateTest.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStepExecutionTest.java
Implement https://github.com/jenkinsci/amazon-ecs-plugin/issues/266
This exposes a new agentContainerName property on templates. This specifies the name of the container that will be used for the Jenkins agent.
=> add agent container name property #266

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloud.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSProvisioningStrategy.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSCloudTest.java
This change aims to fix the issues reported on https://github.com/jenkinsci/amazon-ecs-plugin/issues/269. Essentially when requesting additional agents the `excessWorkload` value is passed regardless of the `maxAgents` limit. When triggering parallel jobs `excessWorkload` may in fact be higher than the number of available agents when `maxAgents` is set.
=> Ensure maxAgents is respected when requesting additional agents.

README.md
The `ecs:ListTagsForResource` permission is required to run a Jenkins agent in ECS.
Here's a sample Jenkins error log when the permission is missing:
```
[ecs-cloud-ecs-8thbs]: Error in provisioning; agent=com.cloudbees.jenkins.plugins.amazonecs.ECSSlave[ecs-cloud-ecs-8thbs]
com.amazonaws.services.ecs.model.AccessDeniedException: User: arn:aws:sts::299404798587:assumed-role/jenkins-role/0bb4884c56ce41ffb16659f56041491f is not authorized to perform: ecs:ListTagsForResource on resource: arn:aws:ecs:eu-west-1:299404798587:task-definition/ecs-cloud-jenkins-agent:128 because no identity-based policy allows the ecs:ListTagsForResource action (Service: AmazonECS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 7627432c-e1ac-43d3-9fdf-340b8d30731f; Proxy: null)
```
=> Add missing ecs:ListTagsForResource permission

README.md, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/ECSTaskTemplate/config.jelly
Updated the readme and the ECSTaskTemplate label description on the config.jelly to reflect the ability to set multiple space delimited labels.
=> Update documentation to reflect ability to set multiple labels on ECSTaskTemplate

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncherTest.java
This patch introduces a retry mechanism that improves the robustness of task launch. A common scenario is elastic network interface provisioning timeout.
Currently the task will be retried once at most, and the total launch time is capped at slaveTimeoutInSeconds.
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
=> amazon-ecs plugin: retry transient ECS task launch failures

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlave.java, src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
The number of executors on ECS Agent is currently hardcoded to 1 even though the number of executors is configurable is the ECS Cloud settings. This fix sets the number of executors from the ECS Cloud settings.
Fixes #326 
* Added tests for both default (1) executor and multiple executors.
* Plugin build and tested on our own Jenkins instances. Multiple jobs can be executed in parallel on single ECS Agent.
* Confirmed settings in Script Console:
```groovy
// Print NumExecutors in ECS Cloud settings
println "NumExecutors: " + com.cloudbees.jenkins.plugins.amazonecs.ECSCloud.getByName("ecs").getNumExecutors()
// Result: NumExecutors: 4
// Print NumExecutors in ECS Agent
jenkins.model.Jenkins.instance.nodes.each { node ->
println "NumExecutors: " + node.getNumExecutors()
}
// NumExecutors: 4 …
```
=> [#326] Set number of executors on ECS Agent

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/BaseAWSService.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/RetryCondition.java
This work comes as a followup on my original PR to implement retries with exponential backoff https://github.com/jenkinsci/amazon-ecs-plugin/pull/193
This PR is a minor quality of life improvement for the ECS Plugin. All this PR does is add logging when there are retries to the AWS API. I have been using this at my employer with success, as it has helped us rule out various infrastructure hiccups and slowdowns on our Jenkins setup.
Other users of this plugin that run on the scale of many thousands of jobs a day may find this useful, as the retry logs can act as an indicator for why jobs are stuck in the queue for a few extra minutes (especially when experiencing rate-limiting by AWS).
```[tasklist]
```
=> use custom retry condition to log retries

src/test/java/com/cloudbees/jenkins/plugins/amazonecs/ECSSlaveTest.java
```[tasklist]
```
In our analysis of the project, we observed that the test `ECSSlaveTest.terminate_ThrowsException_ignoreException` and `ECSSlaveTest.terminateRunningTask` contain unnecessary stubbings. 
Unnecessary stubbings are stubbed method calls that were never realized during test execution. Mockito recommends to remove unnecessary stubbings (https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html). 
We propose below a solution to remove the unnecessary stubbings.
=> Removed 2 unnecessary stubbings in ECSSlaveTest.java

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java
This PR allows to use ephemeralStorageSizeInGiB in declarative pipeline as per example
```
agent {
ecs {
inheritFrom 'example-agent'
cpu 1024
memory 2048
ephemeralStorageSizeInGiB 50
image 'jenkins/inbound-agent:latest'
}
}
```
This PR solves issue https://github.com/jenkinsci/amazon-ecs-plugin/issues/337
```[tasklist]
```
=> Add possibility to override ephemeralStorageSizeInGiB from declarative pipeline

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/BaseAWSService.java
Respect the Jenkins No Proxy Host configuration. In our environment we have a proxy configuration to allow our instance to hit some external sites, but since we are running our instance in AWS we would like to use the VPC endpoint for interacting with ECS rather than the traffic going over the internet. Without this change the traffic was attempting to go through our proxy despite us having *.amazonaws.com in the no proxy list and was getting blocked.
Fixes #317
Built the plugin and applied it to our instance and verified that it was working with *.amazonaws.com in our no proxy list.
```[tasklist]
```
=> [#317] Pass noproxy list to the client

pom.xml, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/ECSLauncher.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java, src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSTaskTemplateStep.java, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgentScript-old.groovy, src/main/resources/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgentScript.groovy
Depends on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/762. Supersedes #364, #366, and #368. **Untested** since I did not see any relevant test cases and I presume manual testing would require special setup with an AWS account.
=> Avoid excessive `Closure`s

src/main/java/com/cloudbees/jenkins/plugins/amazonecs/aws/BaseAWSService.java
The AWS SDK expects to use pipe instead of comma for the noproxy list. Introduced by #318 
Fixes #370 
- [ x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x ] Ensure that the pull request title represents the desired changelog entry
- [ x ] Please describe what you did
- [ x ] Link to relevant issues in GitHub or Jira
- [ x ] Link to relevant pull requests, esp. upstream and downstream changes
- [ x ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> [#370] Use the correct separator character for noproxy
